// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/laex/cg2d/model/SlootContent.proto

package com.laex.cg2d.model;

public final class SlootContent {
  private SlootContent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SlootItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional string title = 2;
    /**
     * <code>optional string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string imgUrl = 3;
    /**
     * <code>optional string imgUrl = 3;</code>
     */
    boolean hasImgUrl();
    /**
     * <code>optional string imgUrl = 3;</code>
     */
    java.lang.String getImgUrl();
    /**
     * <code>optional string imgUrl = 3;</code>
     */
    com.google.protobuf.ByteString
        getImgUrlBytes();

    // optional float price = 4;
    /**
     * <code>optional float price = 4;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional float price = 4;</code>
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code com.laex.cg2d.model.SlootItem}
   *
   * <pre>
   * Sloot Item 
   * </pre>
   */
  public static final class SlootItem extends
      com.google.protobuf.GeneratedMessage
      implements SlootItemOrBuilder {
    // Use SlootItem.newBuilder() to construct.
    private SlootItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SlootItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SlootItem defaultInstance;
    public static SlootItem getDefaultInstance() {
      return defaultInstance;
    }

    public SlootItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SlootItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              imgUrl_ = input.readBytes();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              price_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.laex.cg2d.model.SlootContent.SlootItem.class, com.laex.cg2d.model.SlootContent.SlootItem.Builder.class);
    }

    public static com.google.protobuf.Parser<SlootItem> PARSER =
        new com.google.protobuf.AbstractParser<SlootItem>() {
      public SlootItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SlootItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SlootItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string imgUrl = 3;
    public static final int IMGURL_FIELD_NUMBER = 3;
    private java.lang.Object imgUrl_;
    /**
     * <code>optional string imgUrl = 3;</code>
     */
    public boolean hasImgUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string imgUrl = 3;</code>
     */
    public java.lang.String getImgUrl() {
      java.lang.Object ref = imgUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imgUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imgUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImgUrlBytes() {
      java.lang.Object ref = imgUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imgUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float price = 4;
    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_;
    /**
     * <code>optional float price = 4;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float price = 4;</code>
     */
    public float getPrice() {
      return price_;
    }

    private void initFields() {
      id_ = "";
      title_ = "";
      imgUrl_ = "";
      price_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImgUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, price_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImgUrlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.laex.cg2d.model.SlootContent.SlootItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.laex.cg2d.model.SlootContent.SlootItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.laex.cg2d.model.SlootItem}
     *
     * <pre>
     * Sloot Item 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.laex.cg2d.model.SlootContent.SlootItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.laex.cg2d.model.SlootContent.SlootItem.class, com.laex.cg2d.model.SlootContent.SlootItem.Builder.class);
      }

      // Construct using com.laex.cg2d.model.SlootContent.SlootItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        imgUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootItem_descriptor;
      }

      public com.laex.cg2d.model.SlootContent.SlootItem getDefaultInstanceForType() {
        return com.laex.cg2d.model.SlootContent.SlootItem.getDefaultInstance();
      }

      public com.laex.cg2d.model.SlootContent.SlootItem build() {
        com.laex.cg2d.model.SlootContent.SlootItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.laex.cg2d.model.SlootContent.SlootItem buildPartial() {
        com.laex.cg2d.model.SlootContent.SlootItem result = new com.laex.cg2d.model.SlootContent.SlootItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imgUrl_ = imgUrl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.price_ = price_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laex.cg2d.model.SlootContent.SlootItem) {
          return mergeFrom((com.laex.cg2d.model.SlootContent.SlootItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laex.cg2d.model.SlootContent.SlootItem other) {
        if (other == com.laex.cg2d.model.SlootContent.SlootItem.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasImgUrl()) {
          bitField0_ |= 0x00000004;
          imgUrl_ = other.imgUrl_;
          onChanged();
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.laex.cg2d.model.SlootContent.SlootItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.laex.cg2d.model.SlootContent.SlootItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional string title = 2;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      // optional string imgUrl = 3;
      private java.lang.Object imgUrl_ = "";
      /**
       * <code>optional string imgUrl = 3;</code>
       */
      public boolean hasImgUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string imgUrl = 3;</code>
       */
      public java.lang.String getImgUrl() {
        java.lang.Object ref = imgUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          imgUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imgUrl = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImgUrlBytes() {
        java.lang.Object ref = imgUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imgUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imgUrl = 3;</code>
       */
      public Builder setImgUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imgUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imgUrl = 3;</code>
       */
      public Builder clearImgUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imgUrl_ = getDefaultInstance().getImgUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imgUrl = 3;</code>
       */
      public Builder setImgUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imgUrl_ = value;
        onChanged();
        return this;
      }

      // optional float price = 4;
      private float price_ ;
      /**
       * <code>optional float price = 4;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float price = 4;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>optional float price = 4;</code>
       */
      public Builder setPrice(float value) {
        bitField0_ |= 0x00000008;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float price = 4;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.laex.cg2d.model.SlootItem)
    }

    static {
      defaultInstance = new SlootItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.laex.cg2d.model.SlootItem)
  }

  public interface SlootCollectionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string developerId = 1;
    /**
     * <code>optional string developerId = 1;</code>
     */
    boolean hasDeveloperId();
    /**
     * <code>optional string developerId = 1;</code>
     */
    java.lang.String getDeveloperId();
    /**
     * <code>optional string developerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeveloperIdBytes();

    // optional string collectionTitle = 2;
    /**
     * <code>optional string collectionTitle = 2;</code>
     */
    boolean hasCollectionTitle();
    /**
     * <code>optional string collectionTitle = 2;</code>
     */
    java.lang.String getCollectionTitle();
    /**
     * <code>optional string collectionTitle = 2;</code>
     */
    com.google.protobuf.ByteString
        getCollectionTitleBytes();

    // repeated .com.laex.cg2d.model.SlootItem slootItems = 3;
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    java.util.List<com.laex.cg2d.model.SlootContent.SlootItem> 
        getSlootItemsList();
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    com.laex.cg2d.model.SlootContent.SlootItem getSlootItems(int index);
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    int getSlootItemsCount();
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    java.util.List<? extends com.laex.cg2d.model.SlootContent.SlootItemOrBuilder> 
        getSlootItemsOrBuilderList();
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    com.laex.cg2d.model.SlootContent.SlootItemOrBuilder getSlootItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.laex.cg2d.model.SlootCollection}
   *
   * <pre>
   * Collection of Items 
   * </pre>
   */
  public static final class SlootCollection extends
      com.google.protobuf.GeneratedMessage
      implements SlootCollectionOrBuilder {
    // Use SlootCollection.newBuilder() to construct.
    private SlootCollection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SlootCollection(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SlootCollection defaultInstance;
    public static SlootCollection getDefaultInstance() {
      return defaultInstance;
    }

    public SlootCollection getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SlootCollection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              developerId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              collectionTitle_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                slootItems_ = new java.util.ArrayList<com.laex.cg2d.model.SlootContent.SlootItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              slootItems_.add(input.readMessage(com.laex.cg2d.model.SlootContent.SlootItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          slootItems_ = java.util.Collections.unmodifiableList(slootItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootCollection_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.laex.cg2d.model.SlootContent.SlootCollection.class, com.laex.cg2d.model.SlootContent.SlootCollection.Builder.class);
    }

    public static com.google.protobuf.Parser<SlootCollection> PARSER =
        new com.google.protobuf.AbstractParser<SlootCollection>() {
      public SlootCollection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SlootCollection(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SlootCollection> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string developerId = 1;
    public static final int DEVELOPERID_FIELD_NUMBER = 1;
    private java.lang.Object developerId_;
    /**
     * <code>optional string developerId = 1;</code>
     */
    public boolean hasDeveloperId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string developerId = 1;</code>
     */
    public java.lang.String getDeveloperId() {
      java.lang.Object ref = developerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          developerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string developerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeveloperIdBytes() {
      java.lang.Object ref = developerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        developerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string collectionTitle = 2;
    public static final int COLLECTIONTITLE_FIELD_NUMBER = 2;
    private java.lang.Object collectionTitle_;
    /**
     * <code>optional string collectionTitle = 2;</code>
     */
    public boolean hasCollectionTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string collectionTitle = 2;</code>
     */
    public java.lang.String getCollectionTitle() {
      java.lang.Object ref = collectionTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          collectionTitle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string collectionTitle = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCollectionTitleBytes() {
      java.lang.Object ref = collectionTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.laex.cg2d.model.SlootItem slootItems = 3;
    public static final int SLOOTITEMS_FIELD_NUMBER = 3;
    private java.util.List<com.laex.cg2d.model.SlootContent.SlootItem> slootItems_;
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    public java.util.List<com.laex.cg2d.model.SlootContent.SlootItem> getSlootItemsList() {
      return slootItems_;
    }
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    public java.util.List<? extends com.laex.cg2d.model.SlootContent.SlootItemOrBuilder> 
        getSlootItemsOrBuilderList() {
      return slootItems_;
    }
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    public int getSlootItemsCount() {
      return slootItems_.size();
    }
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    public com.laex.cg2d.model.SlootContent.SlootItem getSlootItems(int index) {
      return slootItems_.get(index);
    }
    /**
     * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
     */
    public com.laex.cg2d.model.SlootContent.SlootItemOrBuilder getSlootItemsOrBuilder(
        int index) {
      return slootItems_.get(index);
    }

    private void initFields() {
      developerId_ = "";
      collectionTitle_ = "";
      slootItems_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeveloperIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCollectionTitleBytes());
      }
      for (int i = 0; i < slootItems_.size(); i++) {
        output.writeMessage(3, slootItems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeveloperIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCollectionTitleBytes());
      }
      for (int i = 0; i < slootItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, slootItems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.laex.cg2d.model.SlootContent.SlootCollection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.laex.cg2d.model.SlootContent.SlootCollection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.laex.cg2d.model.SlootCollection}
     *
     * <pre>
     * Collection of Items 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.laex.cg2d.model.SlootContent.SlootCollectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootCollection_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.laex.cg2d.model.SlootContent.SlootCollection.class, com.laex.cg2d.model.SlootContent.SlootCollection.Builder.class);
      }

      // Construct using com.laex.cg2d.model.SlootContent.SlootCollection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSlootItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        developerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        collectionTitle_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (slootItemsBuilder_ == null) {
          slootItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          slootItemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.laex.cg2d.model.SlootContent.internal_static_com_laex_cg2d_model_SlootCollection_descriptor;
      }

      public com.laex.cg2d.model.SlootContent.SlootCollection getDefaultInstanceForType() {
        return com.laex.cg2d.model.SlootContent.SlootCollection.getDefaultInstance();
      }

      public com.laex.cg2d.model.SlootContent.SlootCollection build() {
        com.laex.cg2d.model.SlootContent.SlootCollection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.laex.cg2d.model.SlootContent.SlootCollection buildPartial() {
        com.laex.cg2d.model.SlootContent.SlootCollection result = new com.laex.cg2d.model.SlootContent.SlootCollection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.developerId_ = developerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.collectionTitle_ = collectionTitle_;
        if (slootItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            slootItems_ = java.util.Collections.unmodifiableList(slootItems_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.slootItems_ = slootItems_;
        } else {
          result.slootItems_ = slootItemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laex.cg2d.model.SlootContent.SlootCollection) {
          return mergeFrom((com.laex.cg2d.model.SlootContent.SlootCollection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laex.cg2d.model.SlootContent.SlootCollection other) {
        if (other == com.laex.cg2d.model.SlootContent.SlootCollection.getDefaultInstance()) return this;
        if (other.hasDeveloperId()) {
          bitField0_ |= 0x00000001;
          developerId_ = other.developerId_;
          onChanged();
        }
        if (other.hasCollectionTitle()) {
          bitField0_ |= 0x00000002;
          collectionTitle_ = other.collectionTitle_;
          onChanged();
        }
        if (slootItemsBuilder_ == null) {
          if (!other.slootItems_.isEmpty()) {
            if (slootItems_.isEmpty()) {
              slootItems_ = other.slootItems_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSlootItemsIsMutable();
              slootItems_.addAll(other.slootItems_);
            }
            onChanged();
          }
        } else {
          if (!other.slootItems_.isEmpty()) {
            if (slootItemsBuilder_.isEmpty()) {
              slootItemsBuilder_.dispose();
              slootItemsBuilder_ = null;
              slootItems_ = other.slootItems_;
              bitField0_ = (bitField0_ & ~0x00000004);
              slootItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSlootItemsFieldBuilder() : null;
            } else {
              slootItemsBuilder_.addAllMessages(other.slootItems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.laex.cg2d.model.SlootContent.SlootCollection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.laex.cg2d.model.SlootContent.SlootCollection) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string developerId = 1;
      private java.lang.Object developerId_ = "";
      /**
       * <code>optional string developerId = 1;</code>
       */
      public boolean hasDeveloperId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string developerId = 1;</code>
       */
      public java.lang.String getDeveloperId() {
        java.lang.Object ref = developerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          developerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string developerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeveloperIdBytes() {
        java.lang.Object ref = developerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          developerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string developerId = 1;</code>
       */
      public Builder setDeveloperId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        developerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string developerId = 1;</code>
       */
      public Builder clearDeveloperId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        developerId_ = getDefaultInstance().getDeveloperId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string developerId = 1;</code>
       */
      public Builder setDeveloperIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        developerId_ = value;
        onChanged();
        return this;
      }

      // optional string collectionTitle = 2;
      private java.lang.Object collectionTitle_ = "";
      /**
       * <code>optional string collectionTitle = 2;</code>
       */
      public boolean hasCollectionTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string collectionTitle = 2;</code>
       */
      public java.lang.String getCollectionTitle() {
        java.lang.Object ref = collectionTitle_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          collectionTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string collectionTitle = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCollectionTitleBytes() {
        java.lang.Object ref = collectionTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collectionTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string collectionTitle = 2;</code>
       */
      public Builder setCollectionTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        collectionTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string collectionTitle = 2;</code>
       */
      public Builder clearCollectionTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        collectionTitle_ = getDefaultInstance().getCollectionTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string collectionTitle = 2;</code>
       */
      public Builder setCollectionTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        collectionTitle_ = value;
        onChanged();
        return this;
      }

      // repeated .com.laex.cg2d.model.SlootItem slootItems = 3;
      private java.util.List<com.laex.cg2d.model.SlootContent.SlootItem> slootItems_ =
        java.util.Collections.emptyList();
      private void ensureSlootItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          slootItems_ = new java.util.ArrayList<com.laex.cg2d.model.SlootContent.SlootItem>(slootItems_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.laex.cg2d.model.SlootContent.SlootItem, com.laex.cg2d.model.SlootContent.SlootItem.Builder, com.laex.cg2d.model.SlootContent.SlootItemOrBuilder> slootItemsBuilder_;

      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public java.util.List<com.laex.cg2d.model.SlootContent.SlootItem> getSlootItemsList() {
        if (slootItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(slootItems_);
        } else {
          return slootItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public int getSlootItemsCount() {
        if (slootItemsBuilder_ == null) {
          return slootItems_.size();
        } else {
          return slootItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public com.laex.cg2d.model.SlootContent.SlootItem getSlootItems(int index) {
        if (slootItemsBuilder_ == null) {
          return slootItems_.get(index);
        } else {
          return slootItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder setSlootItems(
          int index, com.laex.cg2d.model.SlootContent.SlootItem value) {
        if (slootItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlootItemsIsMutable();
          slootItems_.set(index, value);
          onChanged();
        } else {
          slootItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder setSlootItems(
          int index, com.laex.cg2d.model.SlootContent.SlootItem.Builder builderForValue) {
        if (slootItemsBuilder_ == null) {
          ensureSlootItemsIsMutable();
          slootItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          slootItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder addSlootItems(com.laex.cg2d.model.SlootContent.SlootItem value) {
        if (slootItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlootItemsIsMutable();
          slootItems_.add(value);
          onChanged();
        } else {
          slootItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder addSlootItems(
          int index, com.laex.cg2d.model.SlootContent.SlootItem value) {
        if (slootItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSlootItemsIsMutable();
          slootItems_.add(index, value);
          onChanged();
        } else {
          slootItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder addSlootItems(
          com.laex.cg2d.model.SlootContent.SlootItem.Builder builderForValue) {
        if (slootItemsBuilder_ == null) {
          ensureSlootItemsIsMutable();
          slootItems_.add(builderForValue.build());
          onChanged();
        } else {
          slootItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder addSlootItems(
          int index, com.laex.cg2d.model.SlootContent.SlootItem.Builder builderForValue) {
        if (slootItemsBuilder_ == null) {
          ensureSlootItemsIsMutable();
          slootItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          slootItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder addAllSlootItems(
          java.lang.Iterable<? extends com.laex.cg2d.model.SlootContent.SlootItem> values) {
        if (slootItemsBuilder_ == null) {
          ensureSlootItemsIsMutable();
          super.addAll(values, slootItems_);
          onChanged();
        } else {
          slootItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder clearSlootItems() {
        if (slootItemsBuilder_ == null) {
          slootItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          slootItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public Builder removeSlootItems(int index) {
        if (slootItemsBuilder_ == null) {
          ensureSlootItemsIsMutable();
          slootItems_.remove(index);
          onChanged();
        } else {
          slootItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public com.laex.cg2d.model.SlootContent.SlootItem.Builder getSlootItemsBuilder(
          int index) {
        return getSlootItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public com.laex.cg2d.model.SlootContent.SlootItemOrBuilder getSlootItemsOrBuilder(
          int index) {
        if (slootItemsBuilder_ == null) {
          return slootItems_.get(index);  } else {
          return slootItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public java.util.List<? extends com.laex.cg2d.model.SlootContent.SlootItemOrBuilder> 
           getSlootItemsOrBuilderList() {
        if (slootItemsBuilder_ != null) {
          return slootItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(slootItems_);
        }
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public com.laex.cg2d.model.SlootContent.SlootItem.Builder addSlootItemsBuilder() {
        return getSlootItemsFieldBuilder().addBuilder(
            com.laex.cg2d.model.SlootContent.SlootItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public com.laex.cg2d.model.SlootContent.SlootItem.Builder addSlootItemsBuilder(
          int index) {
        return getSlootItemsFieldBuilder().addBuilder(
            index, com.laex.cg2d.model.SlootContent.SlootItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.laex.cg2d.model.SlootItem slootItems = 3;</code>
       */
      public java.util.List<com.laex.cg2d.model.SlootContent.SlootItem.Builder> 
           getSlootItemsBuilderList() {
        return getSlootItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.laex.cg2d.model.SlootContent.SlootItem, com.laex.cg2d.model.SlootContent.SlootItem.Builder, com.laex.cg2d.model.SlootContent.SlootItemOrBuilder> 
          getSlootItemsFieldBuilder() {
        if (slootItemsBuilder_ == null) {
          slootItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.laex.cg2d.model.SlootContent.SlootItem, com.laex.cg2d.model.SlootContent.SlootItem.Builder, com.laex.cg2d.model.SlootContent.SlootItemOrBuilder>(
                  slootItems_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          slootItems_ = null;
        }
        return slootItemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.laex.cg2d.model.SlootCollection)
    }

    static {
      defaultInstance = new SlootCollection(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.laex.cg2d.model.SlootCollection)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_laex_cg2d_model_SlootItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_laex_cg2d_model_SlootItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_laex_cg2d_model_SlootCollection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_laex_cg2d_model_SlootCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&com/laex/cg2d/model/SlootContent.proto" +
      "\022\023com.laex.cg2d.model\"E\n\tSlootItem\022\n\n\002id" +
      "\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\016\n\006imgUrl\030\003 \001(\t\022\r\n" +
      "\005price\030\004 \001(\002\"s\n\017SlootCollection\022\023\n\013devel" +
      "operId\030\001 \001(\t\022\027\n\017collectionTitle\030\002 \001(\t\0222\n" +
      "\nslootItems\030\003 \003(\0132\036.com.laex.cg2d.model." +
      "SlootItem"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_laex_cg2d_model_SlootItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_laex_cg2d_model_SlootItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_laex_cg2d_model_SlootItem_descriptor,
              new java.lang.String[] { "Id", "Title", "ImgUrl", "Price", });
          internal_static_com_laex_cg2d_model_SlootCollection_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_laex_cg2d_model_SlootCollection_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_laex_cg2d_model_SlootCollection_descriptor,
              new java.lang.String[] { "DeveloperId", "CollectionTitle", "SlootItems", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
