# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/laex/cg2d/SlootContent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='com/laex/cg2d/SlootContent.proto',
  package='',
  serialized_pb='\n com/laex/cg2d/SlootContent.proto')





# @@protoc_insertion_point(module_scope)
